readiness-app/force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/inc_ReportScheduler__c.object-meta.xml
<CustomObject>
    <label>Incontact Report Scheduler</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SchedulerId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incontact Report Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/App_Name__c.field-meta.xml
<CustomField>
    <fullName>App_Name__c</fullName>
    <description>Name of the Analytics App</description>
    <inlineHelpText>Name of the Analytics App</inlineHelpText>
    <label>App Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Productivity</fullName>
            </value>
            <value>
                <fullName>Case Analysis</fullName>
            </value>
            <value>
                <fullName>Voice Quality Analysis</fullName>
            </value>
            <value>
                <fullName>Customer Satisfaction (CSAT)</fullName>
            </value>
            <value>
                <fullName>Lead Conversion Analysis</fullName>
            </value>
            <value>
                <fullName>Opportunity Conversion Analysis</fullName>
            </value>
            <value>
                <fullName>Volume Profit Analysis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/Underlying_Reports__c.field-meta.xml
<CustomField>
    <fullName>Underlying_Reports__c</fullName>
    <label>Underlying Reports</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

einstein-app/main/default/classes/inc_Sch_inContactsDatasetCreation_Test.cls
@isTest
public class inc_Sch_inContactsDatasetCreation_Test {
    
    	@testSetup 
        static void setup() {
            List<inc_ReportScheduler__c> repSchedulerList = new List<inc_ReportScheduler__c>();
            inc_ReportScheduler__c repSchFCR_VA = new inc_ReportScheduler__c();
            repSchFCR_VA.Category__c = 'First Call Resolution';
            repSchFCR_VA.App_Name__c = 'Voice Quality Analysis';
            repSchFCR_VA.Underlying_Reports__c = '13';
            repSchedulerList.add(repSchFCR_VA);
            insert repSchedulerList;
    
        }
    
        static testmethod void execute(){
            inc_Sch_inContactsDatasetCreation sec = new inc_Sch_inContactsDatasetCreation();
            test.startTest();
            String sch ='0 48 * * * ?'; 
            System.schedule('Schedule to test dataset sechdular', sch, sec);
            test.stopTest();
                
            system.assert(true);
    	}

}