readiness-app/force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/inc_ReportScheduler__c.object-meta.xml
<CustomObject>
    <label>Incontact Report Scheduler</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SchedulerId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incontact Report Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/App_Name__c.field-meta.xml
<CustomField>
    <fullName>App_Name__c</fullName>
    <description>Name of the Analytics App</description>
    <inlineHelpText>Name of the Analytics App</inlineHelpText>
    <label>App Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Productivity</fullName>
            </value>
            <value>
                <fullName>Case Analysis</fullName>
            </value>
            <value>
                <fullName>Voice Quality Analysis</fullName>
            </value>
            <value>
                <fullName>Customer Satisfaction (CSAT)</fullName>
            </value>
            <value>
                <fullName>Lead Conversion Analysis</fullName>
            </value>
            <value>
                <fullName>Opportunity Conversion Analysis</fullName>
            </value>
            <value>
                <fullName>Volume Profit Analysis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/Last_Run_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Date__c</fullName>
    <description>Last data synch up date time</description>
    <label>Last Run Date</label>
    <type>DateTime</type>
</CustomField>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/Underlying_Reports__c.field-meta.xml
<CustomField>
    <fullName>Underlying_Reports__c</fullName>
    <label>Underlying Reports</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

readiness-app/force-app/main/default/objects/inc_User_Token__c/inc_User_Token__c.object-meta.xml
<CustomObject>
    <description>Used to store access and refresh tokens for report API calls.</description>
    <label>inContact User Token</label>
    <nameField>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inContact User Token</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

readiness-app/force-app/main/default/objects/inc_User_Token__c/fields/access_token__c.field-meta.xml
<CustomField>
    <fullName>access_token__c</fullName>
    <description>Access token</description>
    <inlineHelpText>Access token</inlineHelpText>
    <label>access token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

readiness-app/force-app/main/default/objects/inc_User_Token__c/fields/Is_Authentication_Successful__c.field-meta.xml
<CustomField>
    <fullName>Is_Authentication_Successful__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Authentication Successful</label>
    <type>Checkbox</type>
</CustomField>

einstein-app/main/default/classes/inc_ReportScheduler_Test.cls
@isTest
public class inc_ReportScheduler_Test {

    @testSetup 
    static void testData() {
        inc_ReportScheduler__c repSchFCR_CA = new inc_ReportScheduler__c();
               repSchFCR_CA.Category__c = 'First Call Resolution';
               repSchFCR_CA.App_Name__c = 'First Call Resolution';
        repSchFCR_CA.Underlying_Reports__c = '13';
        insert repSchFCR_CA;
        inc_User_Token__c token = new inc_User_Token__c();
        token.Is_Authentication_Successful__c = false;
        token.access_token__c = 'dfgdfgdfgdfgdfg';
        insert token;
    }
    
    static testmethod void fetchAppSchInfoTest() {
        
        Map<String,Object> repSchMap = new Map<String,Object>();
        test.startTest();
        inc_ReportScheduler.fetchAppSchInfo(repSchMap);
        List<inc_ReportScheduler__c> repSchList = [SELECT Id, App_Name__c, Underlying_Reports__c, Last_Run_Date__c, Category__c
                                                   FROM inc_ReportScheduler__c limit 1];
        List<inc_ReportScheduler__c> repList = inc_ReportScheduler.fetchAppSchInfoList();
        Map<String,Object> dataSynchMap = new Map<String,Object>();
        dataSynchMap = inc_ReportScheduler.runDataSync(repSchList[0].Id);
        
        system.assert(repSchList.size()==1);
        test.stopTest();
    }
    
    static testmethod void saveSchInfoTest() {
        List<inc_ReportScheduler__c> repSchList = [SELECT Id, App_Name__c, Underlying_Reports__c, Last_Run_Date__c, Category__c
                                                   FROM inc_ReportScheduler__c limit 1];
        test.startTest();
        Map<String,Object> scheduleSynchMap = new Map<String,Object>();
        Map<String,Object> scheduleDataMap = new Map<String,Object>();
        scheduleDataMap.put('Id', repSchList[0].Id);
        scheduleDataMap.put('Frequency', 'Weekly');
        List<Object> daylist = new List<Object>();
        daylist.add('Monday');
        daylist.add('Tuesday');
        scheduleDataMap.put('Scheduled_Day',daylist);
        scheduleDataMap.put('StartDate', string.valueOf(datetime.now())) ;
        scheduleSynchMap = inc_ReportScheduler.saveSchInfo(scheduleDataMap);
        Map<String,Object> dataStatusMap = new Map<String,Object>();
        dataStatusMap = inc_ReportScheduler.getDataStatus(repSchList[0].Id);
        
        system.assert(repSchList.size()==1);
        test.stopTest();
    }
    static testmethod void errorStatusTest() {
        List<inc_ReportScheduler__c> repSchList = [SELECT Id, App_Name__c, Underlying_Reports__c, Last_Run_Date__c, Category__c
                                                   FROM inc_ReportScheduler__c limit 1];
        test.startTest();
        Map<String,Object> errorStatusMap = new Map<String,Object>();
        errorStatusMap = inc_ReportScheduler.getErrorStatus(repSchList[0].Id);
        system.assert(repSchList.size()==1);
        test.stopTest();
    }
}