readiness-app/force-app/main/default/objects/Einstein_App_Config_Internal__mdt/Einstein_App_Config_Internal__mdt.object-meta.xml
<CustomObject>
    <description>Settings to store secured data, that is being used by the application developers only. Subscribers org should not be read / modify this data</description>
    <label>Einstein App Config Internal</label>
    <pluralLabel>Einstein App Config Internals</pluralLabel>
</CustomObject>

readiness-app/force-app/main/default/objects/Einstein_App_Config_Internal__mdt/fields/AppId__c.field-meta.xml
<CustomField>
    <fullName>AppId__c</fullName>
    <description>API ApplicationID</description>
    <inlineHelpText>API ApplicationID</inlineHelpText>
    <label>Application Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

readiness-app/force-app/main/default/objects/Einstein_App_Config_Internal__mdt/fields/AppSecret__c.field-meta.xml
<CustomField>
    <fullName>AppSecret__c</fullName>
    <description>API Application Secret</description>
    <inlineHelpText>API Application Secret</inlineHelpText>
    <label>Application Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

readiness-app/force-app/main/default/classes/AppConfig.cls
public with sharing class AppConfig {
   
    public static String getICBasicAuthorization() {
        String appIdSecret = getICAppIdSecret();
        return ('Basic ' + EncodingUtil.base64Encode(Blob.valueof(appIdSecret)));
    }

    private static String getICAppIdSecret() {
        Einstein_App_Config_Internal__mdt[] data = [SELECT DeveloperName, AppId__c, AppSecret__c  FROM Einstein_App_Config_Internal__mdt WHERE DeveloperName = 'inContact'];
        if (data.isEmpty()) {
            return ('');
        } else {
            return (data.get(0).AppId__c + ':' + data.get(0).AppSecret__c);
        }
    }
}