readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/inc_ReportScheduler__c.object-meta.xml
<CustomObject>
    <label>Incontact Report Scheduler</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SchedulerId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incontact Report Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/App_Name__c.field-meta.xml
<CustomField>
    <fullName>App_Name__c</fullName>
    <description>Name of the Analytics App</description>
    <inlineHelpText>Name of the Analytics App</inlineHelpText>
    <label>App Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Productivity</fullName>
            </value>
            <value>
                <fullName>Case Analysis</fullName>
            </value>
            <value>
                <fullName>Voice Quality Analysis</fullName>
            </value>
            <value>
                <fullName>Customer Satisfaction (CSAT)</fullName>
            </value>
            <value>
                <fullName>Lead Conversion Analysis</fullName>
            </value>
            <value>
                <fullName>Opportunity Conversion Analysis</fullName>
            </value>
            <value>
                <fullName>Volume Profit Analysis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/Underlying_Reports__c.field-meta.xml
<CustomField>
    <fullName>Underlying_Reports__c</fullName>
    <label>Underlying Reports</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

readiness-app/force-app/main/default/objects/inc_ReportScheduler__c/fields/UpdateScheduledJob__c.field-meta.xml
<CustomField>
    <fullName>UpdateScheduledJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Schedule Job</label>
    <type>Checkbox</type>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/InContact_Reports__mdt.object-meta.xml
<CustomObject>
    <description>This is list of various reports that are used for Einstein App.</description>
    <label>InContact Report</label>
    <pluralLabel>InContact Reports</pluralLabel>
</CustomObject>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/ReportId__c.field-meta.xml
<CustomField>
    <fullName>ReportId__c</fullName>
    <description>ReportId</description>
    <inlineHelpText>ReportId</inlineHelpText>
    <label>ReportId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

einstein-app/main/default/classes/inc_Sch_inContactsDatasetCreation.cls
global with sharing class inc_Sch_inContactsDatasetCreation implements Schedulable{
    
    
    global void execute(SchedulableContext sc) {
        inc_ReportScheduler__c repList = [SELECT Id, Underlying_Reports__c, UpdateScheduledJob__c, App_Name__c FROM inc_ReportScheduler__c limit 1];
        
        String appName = repList.App_Name__c.replaceAll(' ', '_');
        List<String> repidList = repList.Underlying_Reports__c.split(',');
        List<Integer> repIdIntList = new List<Integer>();
        for(String repId : repidList){
            repIdIntList.add(Integer.valueOf(repId));
        }
        for(InContact_Reports__mdt repdata : [SELECT Id FROM InContact_Reports__mdt WHERE ReportId__c IN:repIdIntList ]){
            if(!Test.isRunningTest()) {
            	String responseStr = inc_CreateDataset.createDataset(repdata.Id, 'Scheduling Error' , appName);
            }
        }
        
    }
}