readiness-app/force-app/main/default/objects/inc_APIUser_Keys__mdt/inc_APIUser_Keys__mdt.object-meta.xml
<CustomObject>
    <description>Stores Access key and access secret which is used for generating access and refresh tokens for report API&#39;s calls.</description>
    <label>inContact API User Keys</label>
    <pluralLabel>inContact API User Keys</pluralLabel>
</CustomObject>

readiness-app/force-app/main/default/objects/inc_APIUser_Keys__mdt/fields/resourceUrl__c.field-meta.xml
<CustomField>
    <fullName>resourceUrl__c</fullName>
    <description>Resource URL used in API calls. Don&#39;t modify it.</description>
    <label>Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/InContact_Reports__mdt.object-meta.xml
<CustomObject>
    <description>This is list of various reports that are used for Einstein App.</description>
    <label>InContact Report</label>
    <pluralLabel>InContact Reports</pluralLabel>
</CustomObject>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/Dataset_Name__c.field-meta.xml
<CustomField>
    <fullName>Dataset_Name__c</fullName>
    <description>Dataset Name</description>
    <inlineHelpText>Dataset Name</inlineHelpText>
    <label>Dataset Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>endDate</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/fields__c.field-meta.xml
<CustomField>
    <fullName>fields__c</fullName>
    <label>fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/MetaData_Json__c.field-meta.xml
<CustomField>
    <fullName>MetaData_Json__c</fullName>
    <label>MetaData Json</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Http Method</description>
    <inlineHelpText>Http Method</inlineHelpText>
    <label>HTTP Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/Report_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_URL__c</fullName>
    <description>Report URL</description>
    <inlineHelpText>Report URL</inlineHelpText>
    <label>Report URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

readiness-app/force-app/main/default/objects/InContact_Reports__mdt/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>startDate</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

einstein-app/main/default/classes/inc_CreateDataset.cls
global  with sharing class inc_CreateDataset {
        
    @AuraEnabled
    Webservice static Id createDataset(Id recId, String errorId, String appName){
        system.debug('recId === '+ recId);
        InContact_Reports__mdt reportData = [SELECT Id, fields__c, startDate__c, endDate__c, MetaData_Json__c,  Dataset_Name__c, method__c, Report_URL__c  FROM InContact_Reports__mdt WHERE Id = :recId];
        inc_APIUser_Keys__mdt data = [SELECT resourceUrl__c  FROM inc_APIUser_Keys__mdt WHERE DeveloperName = 'inContact'];
  
        String datasetName = reportData.Dataset_Name__c;
        String baseUrl = data.resourceUrl__c;
        String reportUrl = reportData.Report_URL__c;
        String method= reportData.method__c;
        String metadataJson = '';
        if(reportData.MetaData_Json__c !=  null)
			metadataJson = reportData.MetaData_Json__c ;        
        Id jobID = inc_CreateDataset.insertMetaData(datasetName, appName, recId, baseUrl, reportUrl, method, errorId, metadataJson );
        return jobID;
    }
    
    public static String insertMetaData(String datasetName, String appName, Id recId, String baseUrl, String reportUrl, string method, String errorId, String metadataJson){
         
        InsightsExternalData sobj = new InsightsExternalData();
        sobj.Format='Csv';
        sobj.EdgemartAlias = datasetName;
        sobj.EdgemartContainer = appName;
        system.debug('metadataJson === '+ metadataJson);
        if(metadataJson!='' || metadataJson!=null)
        	sobj.MetadataJson = Blob.valueOf(metadataJson);
        sobj.Operation = 'Overwrite';
        sobj.Action = 'None';
        insert sobj;
         Id extDataId = sobj.Id;
        try{
       Id jobID = System.enqueueJob(new inc_EnqueueDataPartInsert(extDataId, recId, baseUrl, reportUrl, method, errorId));
        system.debug('jobID === '+ jobID);
       AsyncApexJob jobInfo = [SELECT Status,NumberOfErrors FROM AsyncApexJob WHERE Id=:jobID];
		system.debug('jobInfo === '+ jobInfo);
        return String.valueOf(jobID);
        }catch(Exception ex){
            return 'ERROR';
        }
        
    }
    
}