readiness-app/force-app/main/default/objects/Authentication_Settings__c/Authentication_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Authentication Settings</label>
</CustomObject>

readiness-app/force-app/main/default/objects/Authentication_Settings__c/fields/authUrl__c.field-meta.xml
<CustomField>
    <fullName>authUrl__c</fullName>
    <description>Authentication server URL</description>
    <inlineHelpText>Authentication server URL</inlineHelpText>
    <label>Authentication URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

readiness-app/force-app/main/default/classes/inc_AuthenticationSettings.cls
public with sharing class inc_AuthenticationSettings {
	private Authentication_Settings__c authSetting;
    public String authUrl { get; set; }

    public inc_AuthenticationSettings(string userId) {        
        authSetting = Authentication_Settings__c.getValues(userId);
        system.debug('authSetting  :: '+authSetting);
        if( authSetting == null ) {
            authSetting = new Authentication_Settings__c(SetupOwnerId = userId);
        }
        authUrl = authSetting.authUrl__c;
    } 
}